experiment:
  decision_rule: unanimity
  timeout_seconds: 300
  max_rounds: 2
defaults:
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-mini
  temperature: 0.5
memory_strategy: recent
output:
  directory: hypothesis_experiments/hypothesis_test_batch_20250715_150427/results
  formats:
  - json
  include_feedback: false
  include_transcript: false
performance:
  parallel_feedback: false
  trace_enabled: true
  debug_mode: false
logging:
  enabled: true
  capture_raw_inputs: true
  capture_raw_outputs: true
  capture_memory_context: true
  capture_memory_steps: true
  include_processing_times: true
experiment_id: test_clean_003
global_temperature: 0.29214464853521815
agents:
- name: Agent_1
  model: gpt-4.1-mini
- name: Agent_2
  model: gpt-4o-mini
- name: Agent_3
  model: gpt-4o-mini
