experiment:
  decision_rule: unanimity
  timeout_seconds: 300
  max_rounds: 5
defaults:
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-mini
  temperature: 0.5
memory_strategy: full
output:
  directory: hypothesis_experiments/hypothesis_test_batch_20250715_130557/results
  formats:
  - json
  include_feedback: false
  include_transcript: false
performance:
  parallel_feedback: false
  trace_enabled: true
  debug_mode: false
logging:
  enabled: true
  capture_raw_inputs: true
  capture_raw_outputs: true
  capture_memory_context: true
  capture_memory_steps: true
  include_processing_times: true
experiment_id: hyp_random_005
individual_temperatures:
- 0.31171107608941095
- 0.5200680211778108
- 0.5467102793432796
agents:
- name: Agent_1
  model: gpt-o4-mini
  temperature: 0.31171107608941095
- name: Agent_2
  model: gemini-flash
  temperature: 0.5200680211778108
- name: Agent_3
  model: grok-4
  temperature: 0.5467102793432796
