experiment:
  decision_rule: unanimity
  timeout_seconds: 300
  max_rounds: 4
defaults:
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-mini
  temperature: 0.5
memory_strategy: recent
output:
  directory: hypothesis_experiments/hypothesis_test_batch_20250715_130557/results
  formats:
  - json
  include_feedback: false
  include_transcript: false
performance:
  parallel_feedback: false
  trace_enabled: true
  debug_mode: false
logging:
  enabled: true
  capture_raw_inputs: true
  capture_raw_outputs: true
  capture_memory_context: true
  capture_memory_steps: true
  include_processing_times: true
experiment_id: hyp_random_006
individual_temperatures:
- 0.0884925020519195
- 0.1959828624191452
- 0.045227288910538066
- 0.32533033076326434
- 0.388677289689482
- 0.2713490317738959
agents:
- name: Agent_1
  model: gemini-pro
  temperature: 0.0884925020519195
- name: Agent_2
  model: claude-sonnet-4
  temperature: 0.1959828624191452
- name: Agent_3
  model: gpt-4.1
  temperature: 0.045227288910538066
- name: Agent_4
  model: deepseek-reasoner
  temperature: 0.32533033076326434
- name: Agent_5
  model: gpt-o4-mini
  temperature: 0.388677289689482
- name: Agent_6
  model: gemini-pro
  temperature: 0.2713490317738959
