experiment_id: batch_001_20250718_103330
global_temperature: 0.5
experiment:
  max_rounds: 10
  decision_rule: unanimity
  timeout_seconds: 300
agents:
- name: Agent_1
  personality: You are a communist.
  model: gpt-4.1-nano
- name: Agent_2
  personality: You are a Robert Nozick.
  model: gpt-4.1-nano
- name: Agent_3
  personality: You are a Robert Nozick.
  model: gpt-4.1-nano
defaults:
  personality: You are a Robert Nozick.
  model: gpt-4.1-nano
output:
  directory: experiment_results
  formats:
  - json
  - csv
  - txt
  include_feedback: true
  include_transcript: true
performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true
