experiment_id: decomposed_memory_test
experiment:
  max_rounds: 2
  decision_rule: unanimity
  timeout_seconds: 300

# Use new decomposed memory strategy
memory_strategy: decomposed

agents:
  - name: "Agent_1"
    model: "gpt-4.1-nano"
    personality: "You are a genderfluid person"
  
  - name: "Agent_2"
    model: "gpt-4.1-nano" 
    personality: "You are a women"
  
  - name: "Agent_3"
    model: "gpt-4.1-nano" 
    personality: "You are a man" 

defaults:
  personality: "You are an agent tasked to design a future society."
  model: "gpt-4.1-nano"

output:
  directory: experiment_results
  formats: [json, csv, txt]
  include_feedback: true