experiment_id: diverse_002_20250716_123841
global_temperature: 0.0
experiment:
  max_rounds: 5
  decision_rule: unanimity
  timeout_seconds: 300
agents:
- name: Agent_1
  personality: You are an economist focused on efficiency and optimal resource allocation.
  model: gpt-4.1
- name: Agent_2
  personality: You are an economist focused on efficiency and optimal resource allocation.
  model: gpt-4.1-nano
- name: Agent_3
  personality: You are a philosopher concerned with justice and fairness for all members
    of society.
  model: gpt-4.1
- name: Agent_4
  personality: You are a philosopher concerned with justice and fairness for all members
    of society.
  model: gpt-4.1-mini
defaults:
  personality: You are an economist focused on efficiency and optimal resource allocation.
  model: claude-3-5-sonnet-20241022
output:
  directory: experiment_results
  formats:
  - json
  - csv
  - txt
  include_feedback: true
  include_transcript: true
performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true
