experiment_id: Lucas Test

experiment:
  decision_rule: unanimity
  max_rounds: 3
  models: ["gpt4.1-mini", "gpt4.1-nano", "gpt4.1-nano"]
  num_agents: 3
  timeout_seconds: 240

personalities:
  - "You are an economist focused on efficiency and optimal resource allocation."
  - "You are a philosopher concerned with justice and fairness for all members of society."
  - "You love to debate just for the sake of it, simply take the opposite view of your fellow debaters "


agents:
  enable_feedback_collection: true
  personality_variation: true
output:
  directory: experiment_results
  formats:
  - json
  - csv
  - txt
  include_feedback: true
  include_transcript: true
performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true
