experiment_id: Lucas Test
global_temperature: 0.0 

experiment:
  max_rounds: 3
  decision_rule: unanimity
  timeout_seconds: 240

agents:
  - name: "Agent_1"
    personality: "You are an  AI."
    model: "gpt-4.1-nano"
  - name: "Boris"
    personality: "You are Boris"
    model: "gpt-4.1-nano"

  - name: "Heidi"
    personality: "You are Heidi and you are bit stupid"
    model: "gpt-4.1-nano"
  
  - name: "Donald"
    personality: "You are Donald, you think that you are smarter than everybody else, but in fact you quite dumb. You use very simple langauge and over the top language."
    model: "gpt-4.1-nano"


defaults:
  personality: "You are an agent tasked to design a future society."
  model: "gpt-4.1-nano"

output:
  directory: experiment_results
  formats:
    - json
    - csv
    - txt
  include_feedback: true
  include_transcript: true

performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true