# Multi-model configuration using different LLMs
experiment_id: multi_model_experiment

experiment:
  num_agents: 4
  max_rounds: 5
  decision_rule: unanimity
  timeout_seconds: 300
  models:
    - gpt-4.1-mini
    - gpt-4.1
    - gpt-4.1-mini
    - gpt-4.1

output:
  directory: experiment_results
  formats:
    - json
    - csv
    - txt
  include_feedback: true
  include_transcript: true

agents:
  personality_variation: true
  confidence_threshold: 0.6
  enable_feedback_collection: true

performance:
  parallel_feedback: true
  trace_enabled: true
  debug_mode: false