experiment_id: prob_test_002_20250716_122601
global_temperature: 0.0
experiment:
  max_rounds: 5
  decision_rule: unanimity
  timeout_seconds: 300
agents:
- name: Agent_1
  personality: You are a pragmatist who focuses on what works in practice rather than
    theory.
  model: gpt-4.1-mini
- name: Agent_2
  personality: You are an economist focused on efficiency and optimal resource allocation.
  model: gpt-4.1-nano
- name: Agent_3
  personality: You are an agent tasked to design a future society.
  model: claude-3-5-sonnet-20241022
- name: Agent_4
  personality: You are a pragmatist who focuses on what works in practice rather than
    theory.
  model: gpt-4.1-mini
defaults:
  personality: You are a pragmatist who focuses on what works in practice rather than
    theory.
  model: gpt-4.1-mini
output:
  directory: experiment_results
  formats:
  - json
  - csv
  - txt
  include_feedback: true
  include_transcript: true
performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true
