# Quick test configuration for rapid validation
experiment_id: quick_test_experiment

experiment:
  num_agents: 3
  max_rounds: 2
  decision_rule: unanimity
  timeout_seconds: 60
  models:
    - gpt-4.1-mini
    - gpt-4.1-mini
    - gpt-4.1-mini

output:
  directory: experiment_results
  formats:
    - json
    - csv
    - txt
  include_feedback: true
  include_transcript: true

agents:
  personality_variation: true
  confidence_threshold: 0.5
  enable_feedback_collection: true

performance:
  parallel_feedback: true
  trace_enabled: true
  debug_mode: false