experiment_id: research_005_20250717_100233
global_temperature: 0.0
experiment:
  max_rounds: 5
  decision_rule: unanimity
  timeout_seconds: 300
agents:
- name: Agent_1
  personality: You are a pragmatist focused on practical outcomes.
  model: gpt-4.1-mini
- name: Agent_2
  personality: You are a deontologist focused on duties and rights.
  model: gpt-4.1-mini
- name: Agent_3
  personality: You are a utilitarian focused on maximizing overall welfare.
  model: gpt-4.1-mini
- name: Agent_4
  personality: You are a utilitarian focused on maximizing overall welfare.
  model: gpt-4.1
- name: Agent_5
  personality: You are a deontologist focused on duties and rights.
  model: gpt-4.1-mini
defaults:
  personality: You are a virtue ethicist focused on character and virtues.
  model: gpt-4.1
output:
  directory: experiment_results
  formats:
  - json
  - csv
  - txt
  include_feedback: true
  include_transcript: true
performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true
