experiment_id: Smart test

experiment:
  max_rounds: 3
  decision_rule: unanimity
  timeout_seconds: 240

agents:
  - name: "Arnold"
    personality: "You are Arnold."
    model: "gpt-4.1"
    
  - name: "Boris"
    personality: "You are Boris"
    model: "gpt-4.1"

  - name: "Heidi"
    personality: "You are Heidi"
    model: "gpt-4.1"
  
  - name: "Donald"
    personality: "You are Donald"
    model: "gpt-4.1"


defaults:
  personality: "You are an agent tasked to design a future society."
  model: "gpt-4.1-nano"

output:
  directory: experiment_results
  formats:
    - json
    - csv
    - txt
  include_feedback: true
  include_transcript: true

performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true