experiment_id: test_config

experiment:
  max_rounds: 3
  decision_rule: unanimity
  timeout_seconds: 120

agents:
  - name: "Agent_1"
  - name: "Agent_2"
  - name: "Agent_3"
  - name: "Agent_4"
  - name: "Agent_5"

defaults:
  personality: "You are an agent tasked to design a future society."
  model: "gpt-4.1-mini"

output:
  directory: experiment_results
  formats:
    - json
    - csv
    - txt
  include_feedback: true
  include_transcript: true

performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true