experiment_id: test_backward_compat_001_20250716_122936
global_temperature: 0.0
experiment:
  max_rounds: 2
  decision_rule: unanimity
  timeout_seconds: 300
agents:
- name: Agent_1
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-nano
- name: Agent_2
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-nano
defaults:
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-nano
output:
  directory: experiment_results
  formats:
  - json
  - csv
  - txt
  include_feedback: true
  include_transcript: true
performance:
  debug_mode: false
  parallel_feedback: true
  trace_enabled: true
