experiment_id: test_logging_fixes
global_temperature: 0.7
experiment:
  max_rounds: 2
  decision_rule: unanimity
  timeout_seconds: 300
agents:
- name: Agent_1
  personality: You are an economist focused on efficiency.
  model: gpt-4.1-nano
  temperature: 0.5
- name: Agent_2
  personality: You are a philosopher focused on fairness.
  model: gpt-4.1-nano
defaults:
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-nano
  temperature: 0.3
output:
  directory: test_results
  formats:
  - json
  include_feedback: true
  include_transcript: true