experiment:
  decision_rule: unanimity
  timeout_seconds: 300
  max_rounds: 5
defaults:
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-mini
  temperature: 0.5
memory_strategy: decomposed
output:
  directory: hypothesis_experiments/hypothesis_test_batch_20250715_131812/results
  formats:
  - json
  include_feedback: false
  include_transcript: false
performance:
  parallel_feedback: false
  trace_enabled: true
  debug_mode: false
logging:
  enabled: true
  capture_raw_inputs: true
  capture_raw_outputs: true
  capture_memory_context: true
  capture_memory_steps: true
  include_processing_times: true
experiment_id: hyp_random_004
individual_temperatures:
- 0.3046137691733707
- 0.09767211400638387
- 0.6842330265121569
agents:
- name: Agent_1
  model: deepseek-chat
  temperature: 0.3046137691733707
- name: Agent_2
  model: o3-mini
  temperature: 0.09767211400638387
- name: Agent_3
  model: deepseek-chat
  temperature: 0.6842330265121569
