experiment:
  decision_rule: unanimity
  timeout_seconds: 300
  max_rounds: 2
defaults:
  personality: You are an agent tasked to design a future society.
  model: gpt-4.1-mini
  temperature: 0.5
memory_strategy: full
output:
  directory: hypothesis_experiments/hypothesis_test_batch_20250715_152159/results
  formats:
  - json
  include_feedback: false
  include_transcript: false
performance:
  parallel_feedback: false
  trace_enabled: true
  debug_mode: false
logging:
  enabled: true
  capture_raw_inputs: true
  capture_raw_outputs: true
  capture_memory_context: true
  capture_memory_steps: true
  include_processing_times: true
experiment_id: test_tuesday-2_008
global_temperature: 0.14092422497476265
agents:
- name: Agent_1
  model: gemini-pro
- name: Agent_2
  model: gpt-4.1-mini
- name: Agent_3
  model: gemini-flash
- name: Agent_4
  model: grok-4
